### ISSUE TITLE
Infografía - Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-1-infografia-Edwin14459-1#1]
[INFOGRAFÍA - EDWIN LÓPEZ SANTIAGO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Edwin14459-1/files/14250032/INFOGRAFIA.-.EDWIN.LOPEZ.SANTIAGO.pdf)

**Comment by 27Fer12** [comment]
20/20 muy bien

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
